# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  Base_Rotary_Joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  Grip1_Joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  Grip2_Joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  Lower_Upper_Joint:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: false
    max_acceleration: 0
  P2_Wrist_Joint:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: false
    max_acceleration: 0
  Rotary_Lower_Joint:
    has_velocity_limits: true
    max_velocity: 50
    has_acceleration_limits: false
    max_acceleration: 0
  Upper_P2_Joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0