
#Controller to control robot arm joints
robot_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: ['Base_Rotary_Joint', 'Rotary_Lower_Joint', 'Lower_Upper_Joint', 'Upper_P2_Joint', 'P2_Wrist_Joint']

#Controller to control end effector joints
hand_ee_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: ['Grip1_Joint', 'Grip2_Joint']

#Controller to continuously publish joint states/positions
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50




